
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('MANGAS', '0005 RAYA AZUL MANGAS', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('ALASILK', 'BLANCO RAYA NEGRA', 'FORRO', '55% POL 45% VISC', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('MANGAS', '002 GRIS', 'FORRO', '100% POLIESTER', 'AGOTADO');
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('XD-R1025', 'RAYA CAFÉ', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('XD-P1234', 'BEIGE', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TH067', 'BLACK', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('XD-P1252', 'GRIS/VINO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('XD-P1136', 'NGO/BCO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('G022', 'REDA AZUL MARINO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('XD-P1056-1', 'ROJO', 'FORRO', '100% POLIESTER', '8.7');
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('G005', 'CUADRO MARINO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('G077', 'TABACO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('MASCOTA', 'AZUL', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('G106', 'CUADRO AZUL', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('XD-P1056-2', 'CUADRO BCO/NGO/GRIS', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('XD-P1155', 'CUADRO AZUL/CAFÉ/BCO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('G075', 'BLUE', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('G017', 'CUADRO ROSA', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('G075', 'BLACK', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TH067', 'BLUE', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('ESTAMPADO I-3', 'DIBUJO ROJO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('ESTAMPADO F4', 'DIBUJO GRIS', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SPY 40 A486316', 'COLOR 18', 'FORRO', '55% POL 45% VISC', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SPY22', 'GREY', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TH002', 'FIUSHA', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('XD-P1070-2', 'TORNASOL MORADO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SARGA 011', 'MARINO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SARGA 014', 'UVA', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TH166', 'BLACK', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('XD-R1226-1', 'BEIGE/AZUL', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('D4', 'BLACK', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('D4', 'MARINO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('XD-R1047-5', 'AZUL', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SJX 39', 'NUM 20', 'FORRO', '55% POL 45% VISC', '3.2');
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('D4 GREY JACQUARD', 'GREY', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('ROMBO 005', 'MILITAR', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('ROMBO 004', 'CAFÉ', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('ROMBO 006', 'KAKI', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('ROMBO 010', 'NEGRO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('ROMBO 003', 'CAPUCHINO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('ROMBO 013', 'ROJO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('ROMBO 012', 'VINO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('ROMBO 011', 'MARINO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('ROMBO 008', 'GRIS MEDIO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('PHUKET', 'C029', 'FORRO', '57% POL 43% VIS', '1.1');
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('JACQUARD', '2806 123-125 XFT', 'FORRO', '57% POL 43% VIS', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('BRAZIL', 'C123 GRIS', 'FORRO', '57% POL 43% VIS', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('KRABI', 'C831 VINO', 'FORRO', '57% POL 43% VIS', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('MUGHETTO ', 'C007 VINO', 'FORRO', '57% POL 43% VIS', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('MUGHETTO ', 'C580 NEGRO', 'FORRO', '57% POL 43% VIS', 'AGOTADO');
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('MUGHETTO ', 'C794 CAFÉ', 'FORRO', '57% POL 43% VIS', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('MUGHETTO ', 'C907 MARINO', 'FORRO', '57% POL 43% VIS', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SARGA PLUS', 'CANELA', 'FORRO', '100% ACETATO', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SARGA PLUS', '10 CEMENTO', 'FORRO', '100% ACETATO', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SARGA PLUS', '017 NEGRO', 'FORRO', '100% ACETATO', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SARGA PLUS', '9 CAFÉ', 'FORRO', '100% ACETATO', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SARGA PLUS', '25 NEGRO', 'FORRO', '100% ACETATO', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SARGA PLUS', '015 GRIS MEDIO', 'FORRO', '100% ACETATO', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SARGA PLUS', 'ARENA', 'FORRO', '100% ACETATO', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SARGA PLUS', 'BEIGE CLARO', 'FORRO', '100% ACETATO', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SARGA PLUS', '016 GRIS OXFORD', 'FORRO', '100% ACETATO', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TAFETA', '030 MARINO', 'FORRO', '100% ACETATO', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('OSAKA', '044 OXFORD', 'FORRO', '100% ACETATO', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('OSAKA', '022 OBISPO', 'FORRO', '100% ACETATO', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('F. AMERICANO ', '06 BEIGE', 'FORRO', '100% ACETATO', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SARGA PLUS', '006 CHOCOLATE', 'FORRO', '100% ACETATO', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SARGA PLUS', 'ROJO', 'FORRO', '100% ACETATO', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SARGA PLUS', '012 MARINO', 'FORRO', '100% ACETATO', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SARGA PLUS', '005 CAFÉ', 'FORRO', '100% ACETATO', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('F. AMERICANO', '033 OXFORD', 'FORRO', '100% ACETATO', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('F. AMERICANO', '47 MARINO.', 'FORRO', '100% ACETATO', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('F. AMERICANO', '028 GRIS', 'FORRO', '100% ACETATO', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('F. AMERICANO', '24 VINO', 'FORRO', '100% ACETATO', '1.5');
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('F. AMERICANO', '38 CAFÉ VER', 'FORRO', '100% ACETATO', '1.5');
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER', '084 CHARCOAL.', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER', '067 MARINO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER', '007 BEIGE', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER', '041 ROJO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER', '074 PLUMBAGO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER', '023 KAKY', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER', '098 UVA', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER', '071 VIOLETA', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER', '083 GRIS MEDIO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER', '086 GRIS OXFORD', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER', '042 BEIGE', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER', '097 BORGOÑA', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER', '078 AZUL CIELO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER', '076 BLANCO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER', '080 GRIS PERLA', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER', '004 CHICLE', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER', '039 SANGRE', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER', '085 NEGRO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER', '082 GRIS MEDIO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER', '012 MANGO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER', '017 HUESO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TOL-60-60 BK ', 'BLACK', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TOL-60-GYDK913', 'GRIS', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('VERDE BOTELLA', 'VERDE BOTELLA', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('AZUL PLUMBAGO', 'AZUL PLUMBAGO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TAFETA ESPECIAL ', 'MARINO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TAFETA ELITE', '02 MARINO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TAFETA ELITE', '24 CHOCOLATE', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TOL-60 ', '519 NAVY ', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TAFETA PREMIUM', '066 PIZARRA OBSCURO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TAFETA ELITE', '81 MARINO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER ', '086 GRIS OXFORD.', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY LAINER ', '084 CHARCOAL', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TAFETA ', '043 NARANJA', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TAFETA ', '003 AMARILLO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TAFETA ', '066 PIZARRA OBSCURO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TAFETA ', '065 PIZARRA', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TAFETA ', '063 AZUL REY', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TAFETA ', '038 VINO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TAFETA ', '070 MARINO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TAFETA ', '083 GRIS MEDIO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY TAFETA', '023 VERDE', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TAFETA ELITE', '69 UVA', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '060 NEGRO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '047 ROSA', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '039 SANGRE', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '037 FIUSHA', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '014  KAKI', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('SILKY TAFETA', '078 MORADO.', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '075 OBISPO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '019 CAFÉ', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '015 CAMELLO', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '068 CIRUELA', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '027 VERDE', 'FORRO', '100% POLIESTER', Null);
INSERT INTO `forros` (`codigo_forro`, `color_forro`, `nombre_forro`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '019 VERDE', 'FORRO', '100% POLIESTER', Null);
-- 129 records

