
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A01', 'T5/651', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A02', 'T5/652', 'REDA', 'SUPER 110´S', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A03', 'T5/649', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A04', 'T5/650', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A06', 'T5/584', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A07', 'T5/585', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A08', 'T5/586', 'REDA', 'SUPER 110´S', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A09', 'T5/607', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A10', 'T5/608', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A12', 'T5/653', 'REDA', 'SUPER 110´S', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A13', 'T5/654', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A14', 'T5/655', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A15', 'T5/656', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A16', 'T5/051', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A17', 'T5/025', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A18', 'T5/034', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A19', 'T5/024', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A20', 'T5/033', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A21', 'T5/022', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A23', 'T5/657', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A24', 'T5/612', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A25', 'T5/658', 'REDA', 'SUPER 110´S', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A26', 'T5/659', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A27', 'T5/660', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A28', 'T5/661', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A30', 'T5/663', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A31', 'T5/664', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A32', 'T5/665', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A33', 'T5/666', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A34', 'T5/667', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A35', 'T5/627', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A36', 'T5/583', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A37', 'T5/579', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A38', 'T5/582', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A40', 'T5/581', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A42', 'T5/628', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A44', 'T5/520', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A45', 'T5/521', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A46', 'T5/287', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A47', 'T5/624', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A48', 'T5/670', 'REDA', 'SUPER 110´S', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A49', 'T5/671', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A50', 'T5/600', 'REDA', 'SUPER 110´S', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A52', 'T5/602', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('A53', 'T5/537', 'REDA', 'SUPER 110´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B02', 'T6/772', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B03', 'T6/773', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B05', 'T6/734', 'REDA', 'SUPER 130´S', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B08', 'T6/751', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B09', 'T6/750', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B10', 'T6/778', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B11', 'T6/735', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B12', 'T6/753', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B13', 'T6/733', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B14', 'T6/729', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B15', 'T6/749', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B17', 'T6/781', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B18', 'T6/739', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B19', 'T6/740', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B20', 'T6/783', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B21', 'T6/784', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B24', 'T6/786', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B25', 'T6/787', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B27', 'T6/789', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B29', 'T6/791', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B30', 'T6/742', 'REDA', 'SUPER 130´S', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B31', 'T6/134', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B32', 'T6/133', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B34', 'T6/743', 'REDA', 'SUPER 130´S', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B35', 'T6/744', 'REDA', 'SUPER 130´S', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B36', 'T6/152', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B37', 'T6/158', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B39', 'T6/718', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B40', 'T6/719', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B41', 'T6/720', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B42', 'T6/722', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B44', 'T6/726', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B46', 'T6/635', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B47', 'T6/634', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B48', 'T6/636', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B49', 'T6/136', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B53', 'T6/793', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B54', 'T6/001', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B55', 'T6/002', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B56', 'T6/156', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B57', 'T6/643', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B58', 'T6/012', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B59', 'T6/794', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B60', 'T6/795', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B61', 'T6/796', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B62', 'T6/670', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B63', 'T6/006', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B64', 'T6/797', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B65', 'T6/728', 'REDA', 'SUPER 130´S', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B66', 'T6/669', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B67', 'T6/192', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B68', 'T6/798', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B69', 'T6/008', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B70', 'T6/451', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B71', 'T6/195', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B72', 'T6/700', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B73', 'T6/701', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('B74', 'T6/697', 'REDA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C01', 'T7/052', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C02', 'T7/053', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C04', 'T7/055', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C05', 'T7/056', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C07', 'T7/010', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C08', 'T7/011', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C11', 'T7/044', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C12', 'T7/015', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C13', 'T7/016', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C14', 'T7/045', 'REDA MAIOR', 'SUPER 150´S', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C15', 'T7/018', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C16', 'T7/019', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C17', 'T7/020', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C18', 'T7/046', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C19', 'T7/047', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C21', 'T7/022', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C22', 'T7/024', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C23', 'T7/023', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C24', 'T7/025', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C25', 'T7/048', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C28', 'T7/031', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C30', 'T7/028', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C31', 'T7/029', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C32', 'T7/049', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C33', 'T7/050', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C34', 'T7/051', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C35', 'T7/034', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C36', 'T7/035', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C37', 'T7/036', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C39', 'T7/038', 'REDA MAIOR', 'SUPER 150´S', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C41', 'T7/040', 'REDA MAIOR', 'SUPER 150´S', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C42', 'T7/041', 'REDA MAIOR', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C45', 'T5/576', 'REDA CEREMONIA', 'SUPER 110´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C46', 'T6/689', 'REDA CEREMONIA', 'SUPER 110´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C47', 'T5/614', 'REDA CEREMONIA', 'SUPER 110´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C48', 'T5/642', 'REDA CEREMONIA', 'SUPER 110´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C49', 'T5/643', 'REDA CEREMONIA', 'SUPER 110´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C50', 'T5/644', 'REDA CEREMONIA', 'SUPER 110´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C51', 'T5/645', 'REDA CEREMONIA', 'SUPER 110´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C52', 'T5/646', 'REDA CEREMONIA', 'SUPER 110´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C53', 'T5/647', 'REDA CEREMONIA', 'SUPER 110´S ', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C54', 'T5/648', 'REDA CEREMONIA', 'SUPER 110´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('C55', 'T6/771', 'REDA CEREMONIA', 'SUPER 130´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1', 'T12/001', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('2', 'T12/002', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('3', 'T12/003', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('4', 'T12/004', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('5', 'T12/005', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('6', 'T12/006', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('7', 'T12/007', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('8', 'T12/008', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('9', 'T12/009', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('10', 'T12/010', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('11', 'T12/011', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('12', 'T12/012', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('13', 'T12/013', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('14', 'T12/014', 'GUABELLO', 'SUPER 130´S ', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('15', 'T12/015', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('16', 'T12/016', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('17', 'T12/017', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('18', 'T12/018', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('19', 'T12/029', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('20', 'T12/019', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('21', 'T12/020', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('22', 'T12/021', 'GUABELLO', 'SUPER 130´S ', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('23', 'T12/022', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('24', 'T12/023', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('25', 'T12/024', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('26', 'T12/025', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('27', 'T12/026', 'GUABELLO', 'SUPER 130´S ', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('28', 'T12/027', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('29', 'T12/028', 'GUABELLO', 'SUPER 130´S ', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('30', 'T11/052', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('31', 'T11/053', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('32', 'T11/041', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('33', 'T11/046', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('34', 'T11/047', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('35', 'T11/048', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('36', 'T11/049', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('37', 'T11/013', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('38', 'T11/014', 'GUABELLO', 'SUPER 150´S', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('39', 'T11/036', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('40', 'T11/015', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('41', 'T11/040', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('42', 'T11/016', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('43', 'T11/017', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('44', 'T11/018', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('45', 'T11/042', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('46', 'T11/010', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('47', 'T11/011', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('48', 'T11/012', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('49', 'T11/008', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('50', 'T11/028', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('51', 'T11/009', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('52', 'T11/035', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('53', 'T11/006', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('54', 'T11/007', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('55', 'T11/055', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('56', 'T11/056', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('57', 'T11/057', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('58', 'T11/058', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('59', 'T11/059', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('60', 'T11/060', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('61', 'T11/045', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('62', 'T11/044', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('63', 'T11/043', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('64', 'T11/024', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('65', 'T11/004', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('66', 'T11/054', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('67', 'T11/003', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('68', 'T11/034', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('69', 'T11/001', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('70', 'T11/025', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('71', 'T11/002', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('72', 'T11/037', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('73', 'T11/021', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('74', 'T11/019', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('75', 'T11/020', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('76', 'T11/050', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('77', 'T11/022', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('78', 'T11/051', 'GUABELLO', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('79', 'T11/023', 'GUABELLO', 'SUPER 150´S', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('80', 'T10/014', 'GUABELLO', 'SUPER 180´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('82', 'T10/002', 'GUABELLO', 'SUPER 180´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('83', 'T10/015', 'GUABELLO', 'SUPER 180´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('86', 'T10/008', 'GUABELLO', 'SUPER 180´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('87', 'T10/009', 'GUABELLO', 'SUPER 180´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('88', 'T10/010', 'GUABELLO', 'SUPER 180´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('89', 'T10/005', 'GUABELLO', 'SUPER 180´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('90', 'T10/011', 'GUABELLO', 'SUPER 180´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('91', 'C11/006', 'GUABELLO PURE CASHMERE', '90% WOOL 10% CASHMERE', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('92', 'C11/007', 'GUABELLO PURE CASHMERE', '90% WOOL 10% CASHMERE', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('93', 'C11/002', 'GUABELLO PURE CASHMERE', '90% WOOL 10% CASHMERE', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('95', 'C11/004', 'GUABELLO PURE CASHMERE', '90% WOOL 10% CASHMERE', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('96', 'C11/005', 'GUABELLO PURE CASHMERE', '90% WOOL 10% CASHMERE', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('97', 'CG/014', 'GUABELLO PURE CASHMERE', 'PURE CASHMERE', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('98', 'CG/011', 'GUABELLO PURE CASHMERE', 'PURE CASHMERE', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('100', 'CG/021', 'GUABELLO PURE CASHMERE', 'PURE CASHMERE', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('102', 'CG/019', 'GUABELLO PURE CASHMERE', 'PURE CASHMERE', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('103', 'CG/008', 'GUABELLO PURE CASHMERE', 'PURE CASHMERE', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('104', 'CG/020', 'GUABELLO PURE CASHMERE', 'PURE CASHMERE', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('105', 'CG/002', 'GUABELLO PURE CASHMERE', 'PURE CASHMERE', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '035-D-4', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '035-M-12', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '038-B-2ALT', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '038-D-4ALT', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '041-A-5ALT', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '041-B-3ALT', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '087-L-21', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '20280-035-B-2', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '20294-227-D-4', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '226-H-10ALT', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '226-H-13ALT', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '226-H-2ALT', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '226-H-3ALT', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '226-I-14ALT', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '226-I-6ALT', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '227-A-1', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '227-A-10', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '227-A-8', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '227-C-3', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '227-C-5', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '227-C-9', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '227-D-12', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '227-D-7', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '434-H-8', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '436-A-9', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '436-B-10', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1992', '436-F-9', 'MASTER CLOTH ', 'SUPER 150´S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2103', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2102', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2101', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2105', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2106', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2140', 'GRANO SMOKING ', 'SUPER 120''S', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2163', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2136', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2170', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2104', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2126', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2157', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2130', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2161', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2129', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2162', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2125', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2168', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2174', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2172', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2166', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2175', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2139', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PRESTIGE', '2167', 'GRANO SMOKING ', 'SUPER 120''S', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('MEDITERRANEO', '101', 'MEDITERRANEO ', '85%LANA 15% SEDA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('MEDITERRANEO', '105', 'MEDITERRANEO ', '85%LANA 15% SEDA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('MEDITERRANEO', '264', 'MEDITERRANEO ', '85%LANA 15% SEDA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('MEDITERRANEO', '235', 'MEDITERRANEO ', '85%LANA 15% SEDA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('MEDITERRANEO', '265', 'MEDITERRANEO ', '85%LANA 15% SEDA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('MEDITERRANEO', '107', 'MEDITERRANEO ', '85%LANA 15% SEDA', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('MEDITERRANEO', '248', 'MEDITERRANEO ', '85%LANA 15% SEDA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('MEDITERRANEO', '246', 'MEDITERRANEO ', '85%LANA 15% SEDA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('MEDITERRANEO', '239', 'MEDITERRANEO ', '85%LANA 15% SEDA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('MEDITERRANEO', '237', 'MEDITERRANEO ', '85%LANA 15% SEDA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('MEDITERRANEO', '258', 'MEDITERRANEO ', '85%LANA 15% SEDA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('MEDITERRANEO', '259', 'MEDITERRANEO ', '85%LANA 15% SEDA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SMOKING', 'NEGRO', 'SMOKING', ' 100% LANA', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SMOKING', 'MARINO', 'SMOKING', ' 100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('NUPCIAL', 'MARINO', 'SMOKING', ' 100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('GRANO OLIMPIA', 'NEGRO', 'GRANO OLIMPIA', ' 55% POL 45% LANA', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3033', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3055', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3023', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3015', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3088', 'WIMBLEDON ', '55% POL 45%LANA', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3017', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3022', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3100', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3012', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3013', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3063', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3068', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3043', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3044', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3050', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3094', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3098', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3095', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3076', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3122', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3065', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3066', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3060', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3059', 'WIMBLEDON ', '55% POL 45%LANA', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3061', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3090', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3113', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3058', 'WIMBLEDON ', '55% POL 45%LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('WIMBLEDO', '3108', 'WIMBLEDON ', '55% POL 45%LANA', 'DESCONTINUADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1691', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1618', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1648', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1652', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1682', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1711', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1660', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1620', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1622', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1642', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1640', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1637', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1614', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1667', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1794', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1788', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1791', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1803', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1612', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1631', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1658', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1680', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1783', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1671', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1636', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1802', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1632', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1801', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1608', 'ROCHESTER', '100% LANA', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1619', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1800', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1781', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1670', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1738', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1653', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1611', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1661', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1646', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1623', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1647', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1778', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1626', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1607', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1624', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1633', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1777', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1634', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1600', 'ROCHESTER', '100% LANA', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1601', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1602', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1603', 'ROCHESTER', '100% LANA', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1605', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1639', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1604', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1606', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1628', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1643', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1638', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1769', 'ROCHESTER', '100% LANA', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1710', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1678', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1645', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1627', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1625', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1774', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1617', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1737', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1655', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1641', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1651', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1616', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1669', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROCHESTER', '1673', 'ROCHESTER', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1421', '9991-0101 OXFORD', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1192', '20040-5FX1013 RAYA GRIS PERLA', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('2616', '200-L-7  RAYA NEGRO', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1113', '000-014 NEGRO', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1290', '192-J-11 RAYA GRIS', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('REDA SPA ', 'MEDIA NOCHE', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1536', '20005-0101 RAYA GIS', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('REDA SPA ', 'OXFORD RAYA ANCHA', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1113', '000-015 PLATA', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1113', '000-006 AZUL', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('REDA SPA ', 'NEGRO RAYA FINITA', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('REDA SPA ', 'MERINO MEDIA NOCHE RAYA FINITA', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('REDA SPA ', 'NEGRO C/RAYA BORDADA', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('REDA SPA ', 'AZUL C/RAYA BORDADA', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('REDA SPA ', 'AZUL MARINO MEDIA NOCHE RAYA ANCHA', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('REDA SPA ', 'MARINO RAYA FINITA', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('REDA SPA ', 'OXFORD CON RAYA', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('REDA SPA ', 'GRIS RAYA DE GIS', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('REDA SPA ', 'BEIGE', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PAILANA ', 'VERDE', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PAILANA ', 'BEIGE', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('1747', '7884-0101 NEGRO', 'ISCO', '100% LANA', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('MANGAS', '0005 RAYA AZUL MANGAS', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ALASILK', 'BLANCO RAYA NEGRA', 'FORRO', '55% POL 45% VISC', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('MANGAS', '002 GRIS', 'FORRO', '100% POLIESTER', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('XD-R1025', 'RAYA CAFÉ', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('XD-P1234', 'BEIGE', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TH067', 'BLACK', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('XD-P1252', 'GRIS/VINO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('XD-P1136', 'NGO/BCO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('G022', 'REDA AZUL MARINO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('XD-P1056-1', 'ROJO', 'FORRO', '100% POLIESTER', '8.7');
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('G005', 'CUADRO MARINO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('G077', 'TABACO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('MASCOTA', 'AZUL', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('G106', 'CUADRO AZUL', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('XD-P1056-2', 'CUADRO BCO/NGO/GRIS', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('XD-P1155', 'CUADRO AZUL/CAFÉ/BCO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('G075', 'BLUE', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('G017', 'CUADRO ROSA', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('G075', 'BLACK', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TH067', 'BLUE', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ESTAMPADO I-3', 'DIBUJO ROJO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ESTAMPADO F4', 'DIBUJO GRIS', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SPY 40 A486316', 'COLOR 18', 'FORRO', '55% POL 45% VISC', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SPY22', 'GREY', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TH002', 'FIUSHA', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('XD-P1070-2', 'TORNASOL MORADO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SARGA 011', 'MARINO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SARGA 014', 'UVA', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TH166', 'BLACK', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('XD-R1226-1', 'BEIGE/AZUL', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('D4', 'BLACK', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('D4', 'MARINO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('XD-R1047-5', 'AZUL', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SJX 39', 'NUM 20', 'FORRO', '55% POL 45% VISC', '3.2');
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('D4 GREY JACQUARD', 'GREY', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROMBO 005', 'MILITAR', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROMBO 004', 'CAFÉ', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROMBO 006', 'KAKI', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROMBO 010', 'NEGRO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROMBO 003', 'CAPUCHINO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROMBO 013', 'ROJO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROMBO 012', 'VINO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROMBO 011', 'MARINO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('ROMBO 008', 'GRIS MEDIO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('PHUKET', 'C029', 'FORRO', '57% POL 43% VIS', '1.1');
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('JACQUARD', '2806 123-125 XFT', 'FORRO', '57% POL 43% VIS', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('BRAZIL', 'C123 GRIS', 'FORRO', '57% POL 43% VIS', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('KRABI', 'C831 VINO', 'FORRO', '57% POL 43% VIS', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('MUGHETTO ', 'C007 VINO', 'FORRO', '57% POL 43% VIS', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('MUGHETTO ', 'C580 NEGRO', 'FORRO', '57% POL 43% VIS', 'AGOTADO');;
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('MUGHETTO ', 'C794 CAFÉ', 'FORRO', '57% POL 43% VIS', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('MUGHETTO ', 'C907 MARINO', 'FORRO', '57% POL 43% VIS', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SARGA PLUS', 'CANELA', 'FORRO', '100% ACETATO', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SARGA PLUS', '10 CEMENTO', 'FORRO', '100% ACETATO', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SARGA PLUS', '017 NEGRO', 'FORRO', '100% ACETATO', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SARGA PLUS', '9 CAFÉ', 'FORRO', '100% ACETATO', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SARGA PLUS', '25 NEGRO', 'FORRO', '100% ACETATO', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SARGA PLUS', '015 GRIS MEDIO', 'FORRO', '100% ACETATO', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SARGA PLUS', 'ARENA', 'FORRO', '100% ACETATO', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SARGA PLUS', 'BEIGE CLARO', 'FORRO', '100% ACETATO', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SARGA PLUS', '016 GRIS OXFORD', 'FORRO', '100% ACETATO', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TAFETA', '030 MARINO', 'FORRO', '100% ACETATO', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('OSAKA', '044 OXFORD', 'FORRO', '100% ACETATO', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('OSAKA', '022 OBISPO', 'FORRO', '100% ACETATO', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('F. AMERICANO ', '06 BEIGE', 'FORRO', '100% ACETATO', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SARGA PLUS', '006 CHOCOLATE', 'FORRO', '100% ACETATO', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SARGA PLUS', 'ROJO', 'FORRO', '100% ACETATO', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SARGA PLUS', '012 MARINO', 'FORRO', '100% ACETATO', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SARGA PLUS', '005 CAFÉ', 'FORRO', '100% ACETATO', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('F. AMERICANO', '033 OXFORD', 'FORRO', '100% ACETATO', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('F. AMERICANO', '47 MARINO.', 'FORRO', '100% ACETATO', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('F. AMERICANO', '028 GRIS', 'FORRO', '100% ACETATO', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('F. AMERICANO', '24 VINO', 'FORRO', '100% ACETATO', '1.5');
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('F. AMERICANO', '38 CAFÉ VER', 'FORRO', '100% ACETATO', '1.5');
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER', '084 CHARCOAL.', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER', '067 MARINO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER', '007 BEIGE', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER', '041 ROJO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER', '074 PLUMBAGO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER', '023 KAKY', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER', '098 UVA', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER', '071 VIOLETA', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER', '083 GRIS MEDIO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER', '086 GRIS OXFORD', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER', '042 BEIGE', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER', '097 BORGOÑA', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER', '078 AZUL CIELO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER', '076 BLANCO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER', '080 GRIS PERLA', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER', '004 CHICLE', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER', '039 SANGRE', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER', '085 NEGRO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER', '082 GRIS MEDIO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER', '012 MANGO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER', '017 HUESO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TOL-60-60 BK ', 'BLACK', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TOL-60-GYDK913', 'GRIS', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('VERDE BOTELLA', 'VERDE BOTELLA', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('AZUL PLUMBAGO', 'AZUL PLUMBAGO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TAFETA ESPECIAL ', 'MARINO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TAFETA ELITE', '02 MARINO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TAFETA ELITE', '24 CHOCOLATE', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TOL-60 ', '519 NAVY ', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TAFETA PREMIUM', '066 PIZARRA OBSCURO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TAFETA ELITE', '81 MARINO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER ', '086 GRIS OXFORD.', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY LAINER ', '084 CHARCOAL', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TAFETA ', '043 NARANJA', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TAFETA ', '003 AMARILLO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TAFETA ', '066 PIZARRA OBSCURO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TAFETA ', '065 PIZARRA', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TAFETA ', '063 AZUL REY', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TAFETA ', '038 VINO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TAFETA ', '070 MARINO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TAFETA ', '083 GRIS MEDIO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY TAFETA', '023 VERDE', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TAFETA ELITE', '69 UVA', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '060 NEGRO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '047 ROSA', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '039 SANGRE', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '037 FIUSHA', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '014  KAKI', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('SILKY TAFETA', '078 MORADO.', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '075 OBISPO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '019 CAFÉ', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '015 CAMELLO', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '068 CIRUELA', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '027 VERDE', 'FORRO', '100% POLIESTER', NULL);
INSERT INTO `telas` (`codigo_tela`, `color_tela`, `nombre_tela`, `composicion`, `estado`) VALUES ('TEFETA LAINER', '019 VERDE', 'FORRO', '100% POLIESTER', NULL);
-- 565 records

